<?php
/**
 * Plugin Name: #Wp Competitions Plugin
 * Plugin URI: https://haysky.com/
 * Description: This plugin code is generated by Haysky Code Generator.
 * Version: 1.0.0
 * Author: Haysky
 * Author URI: https://haysky.com/
 * License: GPLv2 or later
  */
// $wpdb->show_errors(); $wpdb->print_error();
error_reporting(E_ERROR | E_PARSE);

include 'competitions.php';

add_action('admin_menu' , function(){
    add_menu_page('Razorpay Settings','Razorpay Settings','manage_options', 'razorpay_keys_admin', 'razorpay_keys_brs', 'dashicons-admin-users','2');
});

function razorpay_keys_brs(){  include 'razorpay_settings.php'; }